### ISSUE TITLE
cannot filter for confluence field, relation does not exist

### ISSUE THREAD

**Issue by igorsmi** [mesilat/confluence-fields#8]
I installed confluence-fields and created a new custom field referencing to confluence pages according to the instruction video and the manual.
It works fine for creating and editing issues, but unfortunately i cannot search for the custom field.
I checked the Jira logs and i found: 

```
2019-11-07 12:40:50,826 http-nio-8080-exec-18 WARN x.MyUserName 760x399988x1 vxg90m 93.219.33.53,192.168.42.10 /rest/api/2/jql/autocompletedata/suggestions [com.mesilat.confluence-fields] Error getting page names
org.postgresql.util.PSQLException: ERROR: relation "ao_9417fd_supplementary_index" does not exist
  Position: 32
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at com.mesilat.confield.DataServiceImpl.getMatchingPageNames(DataServiceImpl.java:148)
	at com.mesilat.confield.ConfluenceFieldClauseValuesGenerator.getPossibleValues(ConfluenceFieldClauseValuesGenerator.java:25)
	at com.atlassian.jira.rest.internal.jql.FieldAndPredicateAutoCompleteResultGenerator.generateResults(FieldAndPredicateAutoCompleteResultGenerator.java:82)
	at com.atlassian.jira.rest.internal.jql.FieldAndPredicateAutoCompleteResultGenerator.getAutoCompleteResultsForField(FieldAndPredicateAutoCompleteResultGenerator.java:53)
	at com.atlassian.jira.rest.v2.search.SearchAutoCompleteResource.getFieldAutoCompleteForQueryString(SearchAutoCompleteResource.java:135)
```
I remember that i renamed the field at some point, that's why i created a new field just for testing purposes - unfortunately same behavior...

**Comment by mesilat** [comment]
Hi, thanks for reporting
I guess Postgres is case-sensitive to table names. I will check this

**Comment by mesilat** [comment]
Hi,
I tested the plugin with latest Confluence / JIRA and Postgres 9.6 and search worked fine. Could you please specify:

- plugin version
- JIRA version
- Postgres version

Could you also try hotfix at https://github.com/mesilat/confluence-fields/releases/tag/1.0.16 and let me know if this fixes your issue?

**Comment by igorsmi** [comment]
Hey,

thanks for you prompt reaction! 
I installed your hotfix, I can now search for the confluence fields, looking good!

so Plugin Version is now 1.0.16,
![image](https://user-images.githubusercontent.com/12802938/69037582-73516c00-09e8-11ea-962e-20c6aa2c84e6.png)
and Jira is at 8.5.1.
